class Substituicao_3x4:
  def __init__(self, palavra: str):
    self.palavra = palavra
    
  def conversao_Letra(self):
    self.palavra = self.palavra.upper()
    self.palavra = self.palavra.replace(' ','0')
    self.palavra = self.palavra.replace('A','2')
    self.palavra = self.palavra.replace('B','2')
    self.palavra = self.palavra.replace('C','2')
    self.palavra = self.palavra.replace('D','3')
    self.palavra = self.palavra.replace('E','3')
    self.palavra = self.palavra.replace('F','3')
    self.palavra = self.palavra.replace('G','4')
    self.palavra = self.palavra.replace('H','4')
    self.palavra = self.palavra.replace('I','4')
    self.palavra = self.palavra.replace('J','5')
    self.palavra = self.palavra.replace('K','5')
    self.palavra = self.palavra.replace('L','5')
    self.palavra = self.palavra.replace('M','6')
    self.palavra = self.palavra.replace('N','6')
    self.palavra = self.palavra.replace('O','6')
    self.palavra = self.palavra.replace('P','7')
    self.palavra = self.palavra.replace('Q','7')
    self.palavra = self.palavra.replace('R','7')
    self.palavra = self.palavra.replace('S','7')
    self.palavra = self.palavra.replace('T','8')
    self.palavra = self.palavra.replace('U','8')
    self.palavra = self.palavra.replace('V','8')
    self.palavra = self.palavra.replace('W','9')
    self.palavra = self.palavra.replace('X','9')
    self.palavra = self.palavra.replace('Y','9')
    self.palavra = self.palavra.replace('Z','9')

  def conversao_Letra_NS(self):
    self.palavra = self.palavra.upper()
    self.palavra = self.palavra.replace(' ','')
    self.palavra = self.palavra.replace('A','2')
    self.palavra = self.palavra.replace('B','2')
    self.palavra = self.palavra.replace('C','2')
    self.palavra = self.palavra.replace('D','3')
    self.palavra = self.palavra.replace('E','3')
    self.palavra = self.palavra.replace('F','3')
    self.palavra = self.palavra.replace('G','4')
    self.palavra = self.palavra.replace('H','4')
    self.palavra = self.palavra.replace('I','4')
    self.palavra = self.palavra.replace('J','5')
    self.palavra = self.palavra.replace('K','5')
    self.palavra = self.palavra.replace('L','5')
    self.palavra = self.palavra.replace('M','6')
    self.palavra = self.palavra.replace('N','6')
    self.palavra = self.palavra.replace('O','6')
    self.palavra = self.palavra.replace('P','7')
    self.palavra = self.palavra.replace('Q','7')
    self.palavra = self.palavra.replace('R','7')
    self.palavra = self.palavra.replace('S','7')
    self.palavra = self.palavra.replace('T','8')
    self.palavra = self.palavra.replace('U','8')
    self.palavra = self.palavra.replace('V','8')
    self.palavra = self.palavra.replace('W','9')
    self.palavra = self.palavra.replace('X','9')
    self.palavra = self.palavra.replace('Y','9')
    self.palavra = self.palavra.replace('Z','9')